<?php
    $title = 'Edit album';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<?php
    $form = $this->form;
    $form->prepare(); 
    $form->setAttribute('action',$this->url('update',
	    array(
		    'id'=> $this->id,
		)
	));
    echo $this->form()->openTag($form);
?>
<div align ="center">
<div style = "width:500px; border: solid 1px #333333; " align = "left">
                <div style = "background-color:#333333; color:#FFFFFF; padding:3px;"><b>UserInfo</b></div>
				        <div style = "margin:30px" id="UserInfo">
							<?php							
							// Hidden Element to store id
							echo $this->formHidden($form->get('Id'));
						
							?>
							
							<div>
							<label>Firstname: </label>
							<?php 
							// TextBox element to input Name of Asset.
							echo $this->formRow($form->get('firstname')); ?>
							</div>
							
							<div>
							<lable><b>Lastname: </b></lable>
 							<?php
							// TextBox element to input Type of Asset.
							echo $this->formRow($form->get('lastname'));
							?>
							</div>

							<div>
 							<lable><b>Email: </b></lable>
 							<?php
							// TextBox element to input AssetDesc of Asset.
							echo $this->formRow($form->get('email'));
							?>
							</div>


							<div> 
							<lable> <b>Gender: </b></lable>
							<?php
							// TextBox element to input status of Asset.
							echo $this->formRow($form->get('gender'));
							?>
							</div>



							<div> 
							
							<?php
							// TextBox element to input status of Asset.
							echo $this->formHidden($form->get('isleasedout'));
							?>
							</div>


							<div> 
							
							<?php
							// TextBox element to input status of Asset.
							echo $this->formHidden($form->get('roleid'));
							?>
							</div>


							 <div>
 							<lable><b>AssetName: </b></lable>
 							<?php
							// TextBox element to input AssetDesc of Asset.
							echo $this->formRow($form->get('assetid'));
							?>
							</div>
							 


							<div>
							<?php
							// Submit button
							echo $this->formSubmit($form->get('submit'));
							?>
							</div> 
 						</div>
							
					</div>
			    </div>
<?php
// Closing the form tag
echo $this->form()->closeTag();
?>							
